---
- name: Create a user  ans set password
  hosts: all
  become: yes
  tasks:
    - name: Create user for development
      user:
        name: devuser
        password: "{{ 'Devuser@123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        home: /home/devuser
        create_home: yes
    - name: Add devuser to sudoers
      lineinfile:
        path: /etc/sudoers
      afterinsert: 'root ALL=(ALL:ALL) ALL'
      line: 'devuser ALL=(ALL:ALL) NOPASSWD: ALL'